name: Friend Snapshots

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: friend-snapshots
  cancel-in-progress: false

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci || npm i --no-audit --no-fund

      - name: Generate snapshots
        run: npm run snapshot
        env:
          PUPPETEER_SKIP_DOWNLOAD: 'false'
          # Optional overrides; set in repo/organization secrets or env if needed
          # FRIENDS_URL: 'https://your-domain/api/links.json'
          # VIEWPORT_WIDTH: '1366'
          # VIEWPORT_HEIGHT: '768'

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A snapshots
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update friend snapshots [skip ci]"
            git push
          fi

